[2023-03-06 01:37:40,922] {processor.py:153} INFO - Started process (PID=2285) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:37:40,924] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:37:40,925] {logging_mixin.py:115} INFO - [2023-03-06 01:37:40,925] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:37:40,933] {logging_mixin.py:115} INFO - [2023-03-06 01:37:40,931] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:37:40,935] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:37:40,949] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 01:38:11,190] {processor.py:153} INFO - Started process (PID=2315) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:38:11,192] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:38:11,193] {logging_mixin.py:115} INFO - [2023-03-06 01:38:11,193] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:38:11,203] {logging_mixin.py:115} INFO - [2023-03-06 01:38:11,201] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:38:11,205] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:38:11,219] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.033 seconds
[2023-03-06 01:38:41,569] {processor.py:153} INFO - Started process (PID=2336) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:38:41,571] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:38:41,574] {logging_mixin.py:115} INFO - [2023-03-06 01:38:41,574] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:38:41,587] {logging_mixin.py:115} INFO - [2023-03-06 01:38:41,585] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:38:41,588] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:38:41,603] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.039 seconds
[2023-03-06 01:39:11,917] {processor.py:153} INFO - Started process (PID=2357) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:39:11,920] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:39:11,923] {logging_mixin.py:115} INFO - [2023-03-06 01:39:11,923] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:39:11,935] {logging_mixin.py:115} INFO - [2023-03-06 01:39:11,933] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:39:11,937] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:39:11,955] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.042 seconds
[2023-03-06 01:39:42,252] {processor.py:153} INFO - Started process (PID=2378) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:39:42,254] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:39:42,256] {logging_mixin.py:115} INFO - [2023-03-06 01:39:42,256] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:39:42,268] {logging_mixin.py:115} INFO - [2023-03-06 01:39:42,266] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:39:42,270] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:39:42,288] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.041 seconds
[2023-03-06 01:40:12,602] {processor.py:153} INFO - Started process (PID=2408) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:40:12,604] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:40:12,606] {logging_mixin.py:115} INFO - [2023-03-06 01:40:12,606] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:40:12,622] {logging_mixin.py:115} INFO - [2023-03-06 01:40:12,618] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:40:12,624] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:40:12,639] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.042 seconds
[2023-03-06 01:40:42,883] {processor.py:153} INFO - Started process (PID=2438) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:40:42,884] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:40:42,885] {logging_mixin.py:115} INFO - [2023-03-06 01:40:42,885] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:40:42,893] {logging_mixin.py:115} INFO - [2023-03-06 01:40:42,892] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:40:42,895] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:40:42,910] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.031 seconds
[2023-03-06 01:41:13,194] {processor.py:153} INFO - Started process (PID=2459) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:41:13,196] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:41:13,197] {logging_mixin.py:115} INFO - [2023-03-06 01:41:13,197] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:41:13,210] {logging_mixin.py:115} INFO - [2023-03-06 01:41:13,207] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:41:13,211] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:41:13,226] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.038 seconds
[2023-03-06 01:41:43,552] {processor.py:153} INFO - Started process (PID=2480) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:41:43,554] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:41:43,556] {logging_mixin.py:115} INFO - [2023-03-06 01:41:43,556] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:41:43,571] {logging_mixin.py:115} INFO - [2023-03-06 01:41:43,568] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:41:43,572] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:41:43,589] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.042 seconds
[2023-03-06 01:42:13,845] {processor.py:153} INFO - Started process (PID=2519) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:42:13,846] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:42:13,848] {logging_mixin.py:115} INFO - [2023-03-06 01:42:13,848] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:42:13,856] {logging_mixin.py:115} INFO - [2023-03-06 01:42:13,854] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:42:13,858] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:42:13,871] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 01:42:44,192] {processor.py:153} INFO - Started process (PID=2540) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:42:44,194] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:42:44,197] {logging_mixin.py:115} INFO - [2023-03-06 01:42:44,197] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:42:44,213] {logging_mixin.py:115} INFO - [2023-03-06 01:42:44,210] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:42:44,215] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:42:44,232] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.045 seconds
[2023-03-06 01:43:14,511] {processor.py:153} INFO - Started process (PID=2561) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:43:14,512] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:43:14,513] {logging_mixin.py:115} INFO - [2023-03-06 01:43:14,513] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:43:14,522] {logging_mixin.py:115} INFO - [2023-03-06 01:43:14,520] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:43:14,523] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:43:14,537] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 01:43:44,844] {processor.py:153} INFO - Started process (PID=2582) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:43:44,846] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:43:44,848] {logging_mixin.py:115} INFO - [2023-03-06 01:43:44,848] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:43:44,861] {logging_mixin.py:115} INFO - [2023-03-06 01:43:44,858] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:43:44,863] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:43:44,882] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.042 seconds
[2023-03-06 01:44:15,122] {processor.py:153} INFO - Started process (PID=2603) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:44:15,124] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:44:15,126] {logging_mixin.py:115} INFO - [2023-03-06 01:44:15,126] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:44:15,140] {logging_mixin.py:115} INFO - [2023-03-06 01:44:15,138] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:44:15,142] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:44:15,162] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.045 seconds
[2023-03-06 01:44:45,486] {processor.py:153} INFO - Started process (PID=2624) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:44:45,488] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:44:45,490] {logging_mixin.py:115} INFO - [2023-03-06 01:44:45,490] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:44:45,505] {logging_mixin.py:115} INFO - [2023-03-06 01:44:45,503] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:44:45,506] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:44:45,522] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.041 seconds
[2023-03-06 01:45:15,901] {processor.py:153} INFO - Started process (PID=2645) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:45:15,904] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:45:15,906] {logging_mixin.py:115} INFO - [2023-03-06 01:45:15,906] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:45:15,919] {logging_mixin.py:115} INFO - [2023-03-06 01:45:15,917] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:45:15,921] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:45:15,937] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.040 seconds
[2023-03-06 01:45:46,235] {processor.py:153} INFO - Started process (PID=2666) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:45:46,237] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:45:46,239] {logging_mixin.py:115} INFO - [2023-03-06 01:45:46,239] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:45:46,255] {logging_mixin.py:115} INFO - [2023-03-06 01:45:46,252] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:45:46,256] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:45:46,274] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.044 seconds
[2023-03-06 01:46:16,503] {processor.py:153} INFO - Started process (PID=2687) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:46:16,505] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:46:16,506] {logging_mixin.py:115} INFO - [2023-03-06 01:46:16,506] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:46:16,515] {logging_mixin.py:115} INFO - [2023-03-06 01:46:16,514] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:46:16,517] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:46:16,535] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.034 seconds
[2023-03-06 01:46:46,805] {processor.py:153} INFO - Started process (PID=2708) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:46:46,807] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:46:46,809] {logging_mixin.py:115} INFO - [2023-03-06 01:46:46,809] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:46:46,825] {logging_mixin.py:115} INFO - [2023-03-06 01:46:46,822] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:46:46,827] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:46:46,846] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.046 seconds
[2023-03-06 01:47:17,091] {processor.py:153} INFO - Started process (PID=2729) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:47:17,095] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:47:17,097] {logging_mixin.py:115} INFO - [2023-03-06 01:47:17,097] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:47:17,109] {logging_mixin.py:115} INFO - [2023-03-06 01:47:17,107] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:47:17,110] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:47:17,125] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.038 seconds
[2023-03-06 01:47:47,537] {processor.py:153} INFO - Started process (PID=2750) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:47:47,539] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:47:47,540] {logging_mixin.py:115} INFO - [2023-03-06 01:47:47,540] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:47:47,552] {logging_mixin.py:115} INFO - [2023-03-06 01:47:47,549] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:47:47,553] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:47:47,571] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.038 seconds
[2023-03-06 01:48:17,863] {processor.py:153} INFO - Started process (PID=2771) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:48:17,865] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:48:17,866] {logging_mixin.py:115} INFO - [2023-03-06 01:48:17,866] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:48:17,879] {logging_mixin.py:115} INFO - [2023-03-06 01:48:17,876] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:48:17,880] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:48:17,902] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.042 seconds
[2023-03-06 01:48:48,216] {processor.py:153} INFO - Started process (PID=2792) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:48:48,218] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:48:48,219] {logging_mixin.py:115} INFO - [2023-03-06 01:48:48,219] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:48:48,232] {logging_mixin.py:115} INFO - [2023-03-06 01:48:48,229] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:48:48,235] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:48:48,252] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.039 seconds
[2023-03-06 01:49:18,566] {processor.py:153} INFO - Started process (PID=2813) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:49:18,569] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:49:18,571] {logging_mixin.py:115} INFO - [2023-03-06 01:49:18,571] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:49:18,582] {logging_mixin.py:115} INFO - [2023-03-06 01:49:18,580] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:49:18,584] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:49:18,603] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.041 seconds
[2023-03-06 01:49:48,915] {processor.py:153} INFO - Started process (PID=2834) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:49:48,917] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:49:48,919] {logging_mixin.py:115} INFO - [2023-03-06 01:49:48,919] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:49:48,932] {logging_mixin.py:115} INFO - [2023-03-06 01:49:48,930] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:49:48,933] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:49:48,950] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.040 seconds
[2023-03-06 01:50:19,226] {processor.py:153} INFO - Started process (PID=2855) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:50:19,228] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:50:19,229] {logging_mixin.py:115} INFO - [2023-03-06 01:50:19,229] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:50:19,239] {logging_mixin.py:115} INFO - [2023-03-06 01:50:19,237] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:50:19,241] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:50:19,257] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.033 seconds
[2023-03-06 01:50:49,569] {processor.py:153} INFO - Started process (PID=2890) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:50:49,572] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:50:49,574] {logging_mixin.py:115} INFO - [2023-03-06 01:50:49,574] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:50:49,593] {logging_mixin.py:115} INFO - [2023-03-06 01:50:49,589] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:50:49,596] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:50:49,614] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.050 seconds
[2023-03-06 01:51:19,938] {processor.py:153} INFO - Started process (PID=2919) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:51:19,940] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:51:19,942] {logging_mixin.py:115} INFO - [2023-03-06 01:51:19,942] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:51:19,957] {logging_mixin.py:115} INFO - [2023-03-06 01:51:19,955] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:51:19,959] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:51:19,975] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.043 seconds
[2023-03-06 01:51:50,287] {processor.py:153} INFO - Started process (PID=2940) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:51:50,290] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:51:50,292] {logging_mixin.py:115} INFO - [2023-03-06 01:51:50,292] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:51:50,306] {logging_mixin.py:115} INFO - [2023-03-06 01:51:50,304] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:51:50,309] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:51:50,324] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.042 seconds
[2023-03-06 01:52:20,623] {processor.py:153} INFO - Started process (PID=2961) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:52:20,626] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:52:20,628] {logging_mixin.py:115} INFO - [2023-03-06 01:52:20,628] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:52:20,642] {logging_mixin.py:115} INFO - [2023-03-06 01:52:20,640] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:52:20,644] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:52:20,661] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.043 seconds
[2023-03-06 01:52:51,060] {processor.py:153} INFO - Started process (PID=2982) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:52:51,063] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:52:51,065] {logging_mixin.py:115} INFO - [2023-03-06 01:52:51,065] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:52:51,076] {logging_mixin.py:115} INFO - [2023-03-06 01:52:51,074] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:52:51,077] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:52:51,095] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.039 seconds
[2023-03-06 01:53:21,392] {processor.py:153} INFO - Started process (PID=3003) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:53:21,393] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:53:21,394] {logging_mixin.py:115} INFO - [2023-03-06 01:53:21,394] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:53:21,402] {logging_mixin.py:115} INFO - [2023-03-06 01:53:21,401] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:53:21,404] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:53:21,418] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 01:53:51,721] {processor.py:153} INFO - Started process (PID=3024) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:53:51,723] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:53:51,725] {logging_mixin.py:115} INFO - [2023-03-06 01:53:51,725] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:53:51,740] {logging_mixin.py:115} INFO - [2023-03-06 01:53:51,737] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:53:51,741] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:53:51,758] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.041 seconds
[2023-03-06 01:54:22,076] {processor.py:153} INFO - Started process (PID=3045) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:54:22,078] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:54:22,080] {logging_mixin.py:115} INFO - [2023-03-06 01:54:22,080] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:54:22,093] {logging_mixin.py:115} INFO - [2023-03-06 01:54:22,090] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:54:22,094] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:54:22,110] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.039 seconds
[2023-03-06 01:54:52,455] {processor.py:153} INFO - Started process (PID=3066) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:54:52,458] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:54:52,460] {logging_mixin.py:115} INFO - [2023-03-06 01:54:52,460] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:54:52,475] {logging_mixin.py:115} INFO - [2023-03-06 01:54:52,473] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:54:52,476] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:54:52,494] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.043 seconds
[2023-03-06 01:55:22,820] {processor.py:153} INFO - Started process (PID=3087) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:55:22,822] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:55:22,824] {logging_mixin.py:115} INFO - [2023-03-06 01:55:22,824] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:55:22,840] {logging_mixin.py:115} INFO - [2023-03-06 01:55:22,837] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:55:22,842] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:55:22,859] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.044 seconds
[2023-03-06 01:55:53,129] {processor.py:153} INFO - Started process (PID=3108) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:55:53,132] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:55:53,135] {logging_mixin.py:115} INFO - [2023-03-06 01:55:53,134] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:55:53,150] {logging_mixin.py:115} INFO - [2023-03-06 01:55:53,147] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:55:53,152] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:55:53,170] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.046 seconds
[2023-03-06 01:56:23,490] {processor.py:153} INFO - Started process (PID=3129) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:56:23,492] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:56:23,494] {logging_mixin.py:115} INFO - [2023-03-06 01:56:23,494] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:56:23,505] {logging_mixin.py:115} INFO - [2023-03-06 01:56:23,502] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:56:23,507] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:56:23,523] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.037 seconds
[2023-03-06 01:56:53,863] {processor.py:153} INFO - Started process (PID=3150) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:56:53,867] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:56:53,869] {logging_mixin.py:115} INFO - [2023-03-06 01:56:53,869] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:56:53,886] {logging_mixin.py:115} INFO - [2023-03-06 01:56:53,881] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:56:53,888] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:56:53,908] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.049 seconds
[2023-03-06 01:57:24,224] {processor.py:153} INFO - Started process (PID=3171) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:57:24,226] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:57:24,228] {logging_mixin.py:115} INFO - [2023-03-06 01:57:24,228] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:57:24,242] {logging_mixin.py:115} INFO - [2023-03-06 01:57:24,240] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:57:24,244] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:57:24,260] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.041 seconds
[2023-03-06 01:57:54,621] {processor.py:153} INFO - Started process (PID=3192) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:57:54,623] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:57:54,624] {logging_mixin.py:115} INFO - [2023-03-06 01:57:54,624] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:57:54,635] {logging_mixin.py:115} INFO - [2023-03-06 01:57:54,633] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:57:54,637] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:57:54,652] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.036 seconds
[2023-03-06 01:58:24,977] {processor.py:153} INFO - Started process (PID=3213) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:58:24,979] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:58:24,981] {logging_mixin.py:115} INFO - [2023-03-06 01:58:24,981] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:58:24,991] {logging_mixin.py:115} INFO - [2023-03-06 01:58:24,990] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:58:24,993] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:58:25,010] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.035 seconds
[2023-03-06 01:58:55,286] {processor.py:153} INFO - Started process (PID=3234) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:58:55,290] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:58:55,293] {logging_mixin.py:115} INFO - [2023-03-06 01:58:55,292] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:58:55,305] {logging_mixin.py:115} INFO - [2023-03-06 01:58:55,303] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:58:55,307] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:58:55,323] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.041 seconds
[2023-03-06 01:59:25,571] {processor.py:153} INFO - Started process (PID=3255) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:59:25,572] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:59:25,574] {logging_mixin.py:115} INFO - [2023-03-06 01:59:25,574] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:59:25,583] {logging_mixin.py:115} INFO - [2023-03-06 01:59:25,581] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:59:25,584] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:59:25,603] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.036 seconds
[2023-03-06 01:59:55,901] {processor.py:153} INFO - Started process (PID=3276) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:59:55,902] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 01:59:55,903] {logging_mixin.py:115} INFO - [2023-03-06 01:59:55,903] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:59:55,913] {logging_mixin.py:115} INFO - [2023-03-06 01:59:55,911] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 01:59:55,915] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 01:59:55,930] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.032 seconds
[2023-03-06 02:00:26,223] {processor.py:153} INFO - Started process (PID=3297) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:00:26,225] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:00:26,227] {logging_mixin.py:115} INFO - [2023-03-06 02:00:26,227] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:00:26,238] {logging_mixin.py:115} INFO - [2023-03-06 02:00:26,236] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:00:26,240] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:00:26,257] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.038 seconds
[2023-03-06 02:00:56,592] {processor.py:153} INFO - Started process (PID=3318) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:00:56,594] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:00:56,596] {logging_mixin.py:115} INFO - [2023-03-06 02:00:56,596] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:00:56,606] {logging_mixin.py:115} INFO - [2023-03-06 02:00:56,604] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:00:56,608] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:00:56,623] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.036 seconds
[2023-03-06 02:01:26,931] {processor.py:153} INFO - Started process (PID=3339) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:01:26,933] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:01:26,935] {logging_mixin.py:115} INFO - [2023-03-06 02:01:26,935] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:01:26,950] {logging_mixin.py:115} INFO - [2023-03-06 02:01:26,947] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:01:26,954] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:01:26,974] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.047 seconds
[2023-03-06 02:01:57,275] {processor.py:153} INFO - Started process (PID=3360) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:01:57,277] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:01:57,279] {logging_mixin.py:115} INFO - [2023-03-06 02:01:57,279] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:01:57,293] {logging_mixin.py:115} INFO - [2023-03-06 02:01:57,290] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:01:57,295] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:01:57,311] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.041 seconds
[2023-03-06 02:02:27,643] {processor.py:153} INFO - Started process (PID=3381) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:02:27,644] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:02:27,645] {logging_mixin.py:115} INFO - [2023-03-06 02:02:27,645] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:02:27,653] {logging_mixin.py:115} INFO - [2023-03-06 02:02:27,652] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:02:27,655] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:02:27,667] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.027 seconds
[2023-03-06 02:02:58,044] {processor.py:153} INFO - Started process (PID=3402) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:02:58,046] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:02:58,047] {logging_mixin.py:115} INFO - [2023-03-06 02:02:58,047] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:02:58,056] {logging_mixin.py:115} INFO - [2023-03-06 02:02:58,055] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:02:58,058] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:02:58,072] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.030 seconds
[2023-03-06 02:03:28,369] {processor.py:153} INFO - Started process (PID=3423) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:03:28,372] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:03:28,375] {logging_mixin.py:115} INFO - [2023-03-06 02:03:28,374] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:03:28,389] {logging_mixin.py:115} INFO - [2023-03-06 02:03:28,386] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:03:28,391] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:03:28,405] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.042 seconds
[2023-03-06 02:03:58,694] {processor.py:153} INFO - Started process (PID=3444) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:03:58,696] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:03:58,698] {logging_mixin.py:115} INFO - [2023-03-06 02:03:58,698] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:03:58,709] {logging_mixin.py:115} INFO - [2023-03-06 02:03:58,708] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:03:58,711] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:03:58,729] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.038 seconds
[2023-03-06 02:04:29,056] {processor.py:153} INFO - Started process (PID=3465) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:04:29,059] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:04:29,061] {logging_mixin.py:115} INFO - [2023-03-06 02:04:29,061] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:04:29,078] {logging_mixin.py:115} INFO - [2023-03-06 02:04:29,076] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:04:29,081] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:04:29,098] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.047 seconds
[2023-03-06 02:04:59,379] {processor.py:153} INFO - Started process (PID=3486) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:04:59,382] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:04:59,385] {logging_mixin.py:115} INFO - [2023-03-06 02:04:59,384] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:04:59,400] {logging_mixin.py:115} INFO - [2023-03-06 02:04:59,397] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:04:59,401] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:04:59,417] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.043 seconds
[2023-03-06 02:05:29,728] {processor.py:153} INFO - Started process (PID=3507) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:05:29,731] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:05:29,733] {logging_mixin.py:115} INFO - [2023-03-06 02:05:29,733] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:05:29,749] {logging_mixin.py:115} INFO - [2023-03-06 02:05:29,745] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:05:29,752] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:05:29,770] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.048 seconds
[2023-03-06 02:06:00,056] {processor.py:153} INFO - Started process (PID=3528) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:06:00,058] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:06:00,060] {logging_mixin.py:115} INFO - [2023-03-06 02:06:00,060] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:06:00,072] {logging_mixin.py:115} INFO - [2023-03-06 02:06:00,070] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:06:00,074] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:06:00,091] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.039 seconds
[2023-03-06 02:06:30,452] {processor.py:153} INFO - Started process (PID=3549) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:06:30,454] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:06:30,458] {logging_mixin.py:115} INFO - [2023-03-06 02:06:30,458] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:06:30,469] {logging_mixin.py:115} INFO - [2023-03-06 02:06:30,467] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:06:30,470] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:06:30,485] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.038 seconds
[2023-03-06 02:07:00,730] {processor.py:153} INFO - Started process (PID=3570) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:07:00,732] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:07:00,733] {logging_mixin.py:115} INFO - [2023-03-06 02:07:00,733] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:07:00,741] {logging_mixin.py:115} INFO - [2023-03-06 02:07:00,740] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:07:00,742] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:07:00,756] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:07:31,014] {processor.py:153} INFO - Started process (PID=3591) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:07:31,015] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:07:31,017] {logging_mixin.py:115} INFO - [2023-03-06 02:07:31,017] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:07:31,027] {logging_mixin.py:115} INFO - [2023-03-06 02:07:31,024] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:07:31,028] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:07:31,044] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.033 seconds
[2023-03-06 02:08:01,398] {processor.py:153} INFO - Started process (PID=3612) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:08:01,400] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:08:01,402] {logging_mixin.py:115} INFO - [2023-03-06 02:08:01,401] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:08:01,410] {logging_mixin.py:115} INFO - [2023-03-06 02:08:01,408] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:08:01,411] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:08:01,426] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.031 seconds
[2023-03-06 02:08:31,672] {processor.py:153} INFO - Started process (PID=3633) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:08:31,674] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:08:31,675] {logging_mixin.py:115} INFO - [2023-03-06 02:08:31,675] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:08:31,683] {logging_mixin.py:115} INFO - [2023-03-06 02:08:31,682] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:08:31,684] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:08:31,698] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 02:09:01,963] {processor.py:153} INFO - Started process (PID=3654) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:09:01,965] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:09:01,966] {logging_mixin.py:115} INFO - [2023-03-06 02:09:01,966] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:09:01,973] {logging_mixin.py:115} INFO - [2023-03-06 02:09:01,972] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:09:01,975] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:09:01,989] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:09:32,216] {processor.py:153} INFO - Started process (PID=3675) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:09:32,217] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:09:32,218] {logging_mixin.py:115} INFO - [2023-03-06 02:09:32,218] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:09:32,226] {logging_mixin.py:115} INFO - [2023-03-06 02:09:32,224] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:09:32,227] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:09:32,242] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:10:02,481] {processor.py:153} INFO - Started process (PID=3696) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:10:02,482] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:10:02,483] {logging_mixin.py:115} INFO - [2023-03-06 02:10:02,483] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:10:02,491] {logging_mixin.py:115} INFO - [2023-03-06 02:10:02,489] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:10:02,492] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:10:02,506] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.027 seconds
[2023-03-06 02:10:32,756] {processor.py:153} INFO - Started process (PID=3717) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:10:32,758] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:10:32,759] {logging_mixin.py:115} INFO - [2023-03-06 02:10:32,759] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:10:32,766] {logging_mixin.py:115} INFO - [2023-03-06 02:10:32,765] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:10:32,768] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:10:32,782] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:11:03,036] {processor.py:153} INFO - Started process (PID=3738) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:11:03,037] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:11:03,038] {logging_mixin.py:115} INFO - [2023-03-06 02:11:03,037] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:11:03,045] {logging_mixin.py:115} INFO - [2023-03-06 02:11:03,043] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:11:03,047] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:11:03,062] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 02:11:33,278] {processor.py:153} INFO - Started process (PID=3759) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:11:33,279] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:11:33,281] {logging_mixin.py:115} INFO - [2023-03-06 02:11:33,281] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:11:33,289] {logging_mixin.py:115} INFO - [2023-03-06 02:11:33,288] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:11:33,290] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:11:33,303] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.027 seconds
[2023-03-06 02:12:03,554] {processor.py:153} INFO - Started process (PID=3780) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:12:03,555] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:12:03,556] {logging_mixin.py:115} INFO - [2023-03-06 02:12:03,556] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:12:03,564] {logging_mixin.py:115} INFO - [2023-03-06 02:12:03,563] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:12:03,565] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:12:03,578] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.027 seconds
[2023-03-06 02:12:33,865] {processor.py:153} INFO - Started process (PID=3801) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:12:33,867] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:12:33,868] {logging_mixin.py:115} INFO - [2023-03-06 02:12:33,868] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:12:33,878] {logging_mixin.py:115} INFO - [2023-03-06 02:12:33,876] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:12:33,880] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:12:33,896] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.032 seconds
[2023-03-06 02:13:04,216] {processor.py:153} INFO - Started process (PID=3822) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:13:04,218] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:13:04,219] {logging_mixin.py:115} INFO - [2023-03-06 02:13:04,219] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:13:04,228] {logging_mixin.py:115} INFO - [2023-03-06 02:13:04,226] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:13:04,229] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:13:04,242] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:13:34,482] {processor.py:153} INFO - Started process (PID=3843) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:13:34,483] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:13:34,485] {logging_mixin.py:115} INFO - [2023-03-06 02:13:34,485] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:13:34,493] {logging_mixin.py:115} INFO - [2023-03-06 02:13:34,492] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:13:34,495] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:13:34,510] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 02:14:04,731] {processor.py:153} INFO - Started process (PID=3864) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:14:04,734] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:14:04,736] {logging_mixin.py:115} INFO - [2023-03-06 02:14:04,736] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:14:04,747] {logging_mixin.py:115} INFO - [2023-03-06 02:14:04,744] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:14:04,747] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:14:04,766] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.038 seconds
[2023-03-06 02:14:35,052] {processor.py:153} INFO - Started process (PID=3885) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:14:35,054] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:14:35,056] {logging_mixin.py:115} INFO - [2023-03-06 02:14:35,056] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:14:35,066] {logging_mixin.py:115} INFO - [2023-03-06 02:14:35,065] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:14:35,068] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:14:35,082] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.032 seconds
[2023-03-06 02:15:05,309] {processor.py:153} INFO - Started process (PID=3906) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:15:05,310] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:15:05,311] {logging_mixin.py:115} INFO - [2023-03-06 02:15:05,311] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:15:05,323] {logging_mixin.py:115} INFO - [2023-03-06 02:15:05,322] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:15:05,325] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:15:05,338] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.032 seconds
[2023-03-06 02:15:35,614] {processor.py:153} INFO - Started process (PID=3927) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:15:35,616] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:15:35,617] {logging_mixin.py:115} INFO - [2023-03-06 02:15:35,617] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:15:35,629] {logging_mixin.py:115} INFO - [2023-03-06 02:15:35,627] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:15:35,630] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:15:35,645] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.033 seconds
[2023-03-06 02:16:05,886] {processor.py:153} INFO - Started process (PID=3948) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:16:05,888] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:16:05,890] {logging_mixin.py:115} INFO - [2023-03-06 02:16:05,890] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:16:05,898] {logging_mixin.py:115} INFO - [2023-03-06 02:16:05,896] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:16:05,899] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:16:05,913] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 02:16:36,191] {processor.py:153} INFO - Started process (PID=3969) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:16:36,192] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:16:36,193] {logging_mixin.py:115} INFO - [2023-03-06 02:16:36,193] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:16:36,203] {logging_mixin.py:115} INFO - [2023-03-06 02:16:36,201] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:16:36,204] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:16:36,218] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 02:17:06,443] {processor.py:153} INFO - Started process (PID=3990) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:17:06,444] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:17:06,445] {logging_mixin.py:115} INFO - [2023-03-06 02:17:06,445] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:17:06,455] {logging_mixin.py:115} INFO - [2023-03-06 02:17:06,453] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:17:06,456] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:17:06,470] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:17:36,727] {processor.py:153} INFO - Started process (PID=4011) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:17:36,729] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:17:36,730] {logging_mixin.py:115} INFO - [2023-03-06 02:17:36,730] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:17:36,739] {logging_mixin.py:115} INFO - [2023-03-06 02:17:36,737] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:17:36,741] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:17:36,755] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.030 seconds
[2023-03-06 02:18:07,444] {processor.py:153} INFO - Started process (PID=4052) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:18:07,445] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:18:07,446] {logging_mixin.py:115} INFO - [2023-03-06 02:18:07,446] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:18:07,454] {logging_mixin.py:115} INFO - [2023-03-06 02:18:07,452] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:18:07,456] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:18:07,470] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:18:37,971] {processor.py:153} INFO - Started process (PID=4108) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:18:37,973] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:18:37,975] {logging_mixin.py:115} INFO - [2023-03-06 02:18:37,975] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:18:37,982] {logging_mixin.py:115} INFO - [2023-03-06 02:18:37,981] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:18:37,984] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:18:37,997] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:19:08,423] {processor.py:153} INFO - Started process (PID=4164) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:19:08,425] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:19:08,426] {logging_mixin.py:115} INFO - [2023-03-06 02:19:08,426] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:19:08,435] {logging_mixin.py:115} INFO - [2023-03-06 02:19:08,434] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:19:08,437] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:19:08,451] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.030 seconds
[2023-03-06 02:19:38,736] {processor.py:153} INFO - Started process (PID=4190) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:19:38,738] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:19:38,739] {logging_mixin.py:115} INFO - [2023-03-06 02:19:38,739] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:19:38,748] {logging_mixin.py:115} INFO - [2023-03-06 02:19:38,746] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:19:38,749] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:19:38,766] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.032 seconds
[2023-03-06 02:20:08,970] {processor.py:153} INFO - Started process (PID=4216) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:20:08,971] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:20:08,973] {logging_mixin.py:115} INFO - [2023-03-06 02:20:08,973] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:20:08,984] {logging_mixin.py:115} INFO - [2023-03-06 02:20:08,982] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:20:08,986] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:20:09,000] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.032 seconds
[2023-03-06 02:20:39,186] {processor.py:153} INFO - Started process (PID=4242) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:20:39,187] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:20:39,189] {logging_mixin.py:115} INFO - [2023-03-06 02:20:39,189] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:20:39,197] {logging_mixin.py:115} INFO - [2023-03-06 02:20:39,195] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:20:39,200] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:20:39,215] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.032 seconds
[2023-03-06 02:21:09,451] {processor.py:153} INFO - Started process (PID=4268) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:21:09,452] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:21:09,453] {logging_mixin.py:115} INFO - [2023-03-06 02:21:09,453] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:21:09,460] {logging_mixin.py:115} INFO - [2023-03-06 02:21:09,458] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:21:09,461] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:21:09,475] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.026 seconds
[2023-03-06 02:21:39,733] {processor.py:153} INFO - Started process (PID=4294) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:21:39,734] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:21:39,736] {logging_mixin.py:115} INFO - [2023-03-06 02:21:39,736] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:21:39,744] {logging_mixin.py:115} INFO - [2023-03-06 02:21:39,743] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:21:39,745] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:21:39,758] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:22:10,243] {processor.py:153} INFO - Started process (PID=4350) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:22:10,244] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:22:10,246] {logging_mixin.py:115} INFO - [2023-03-06 02:22:10,246] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:22:10,254] {logging_mixin.py:115} INFO - [2023-03-06 02:22:10,252] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:22:10,255] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:22:10,270] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 02:22:40,582] {processor.py:153} INFO - Started process (PID=4376) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:22:40,584] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:22:40,586] {logging_mixin.py:115} INFO - [2023-03-06 02:22:40,586] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:22:40,594] {logging_mixin.py:115} INFO - [2023-03-06 02:22:40,593] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:22:40,596] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:22:40,611] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.031 seconds
[2023-03-06 02:23:10,995] {processor.py:153} INFO - Started process (PID=4407) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:23:10,997] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:23:10,999] {logging_mixin.py:115} INFO - [2023-03-06 02:23:10,999] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:23:11,008] {logging_mixin.py:115} INFO - [2023-03-06 02:23:11,006] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:23:11,009] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:23:11,023] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.031 seconds
[2023-03-06 02:23:41,480] {processor.py:153} INFO - Started process (PID=4443) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:23:41,482] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:23:41,483] {logging_mixin.py:115} INFO - [2023-03-06 02:23:41,483] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:23:41,491] {logging_mixin.py:115} INFO - [2023-03-06 02:23:41,490] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:23:41,492] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:23:41,507] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 02:24:12,160] {processor.py:153} INFO - Started process (PID=4514) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:24:12,163] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:24:12,164] {logging_mixin.py:115} INFO - [2023-03-06 02:24:12,164] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:24:12,172] {logging_mixin.py:115} INFO - [2023-03-06 02:24:12,170] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:24:12,173] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:24:12,187] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.031 seconds
[2023-03-06 02:24:42,517] {processor.py:153} INFO - Started process (PID=4549) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:24:42,518] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:24:42,519] {logging_mixin.py:115} INFO - [2023-03-06 02:24:42,519] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:24:42,527] {logging_mixin.py:115} INFO - [2023-03-06 02:24:42,526] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:24:42,528] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:24:42,543] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:25:12,787] {processor.py:153} INFO - Started process (PID=4575) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:25:12,788] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:25:12,790] {logging_mixin.py:115} INFO - [2023-03-06 02:25:12,790] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:25:12,797] {logging_mixin.py:115} INFO - [2023-03-06 02:25:12,796] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:25:12,799] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:25:12,814] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 02:25:43,106] {processor.py:153} INFO - Started process (PID=4601) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:25:43,108] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:25:43,110] {logging_mixin.py:115} INFO - [2023-03-06 02:25:43,110] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:25:43,119] {logging_mixin.py:115} INFO - [2023-03-06 02:25:43,118] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:25:43,120] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:25:43,136] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.032 seconds
[2023-03-06 02:26:13,422] {processor.py:153} INFO - Started process (PID=4627) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:26:13,424] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:26:13,425] {logging_mixin.py:115} INFO - [2023-03-06 02:26:13,425] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:26:13,432] {logging_mixin.py:115} INFO - [2023-03-06 02:26:13,430] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:26:13,433] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:26:13,447] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.027 seconds
[2023-03-06 02:26:43,729] {processor.py:153} INFO - Started process (PID=4653) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:26:43,730] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:26:43,731] {logging_mixin.py:115} INFO - [2023-03-06 02:26:43,731] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:26:43,738] {logging_mixin.py:115} INFO - [2023-03-06 02:26:43,737] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:26:43,740] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:26:43,753] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.027 seconds
[2023-03-06 02:27:14,006] {processor.py:153} INFO - Started process (PID=4679) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:27:14,008] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:27:14,010] {logging_mixin.py:115} INFO - [2023-03-06 02:27:14,010] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:27:14,019] {logging_mixin.py:115} INFO - [2023-03-06 02:27:14,017] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:27:14,022] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:27:14,037] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.033 seconds
[2023-03-06 02:27:44,337] {processor.py:153} INFO - Started process (PID=4705) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:27:44,339] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:27:44,340] {logging_mixin.py:115} INFO - [2023-03-06 02:27:44,340] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:27:44,349] {logging_mixin.py:115} INFO - [2023-03-06 02:27:44,347] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:27:44,351] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:27:44,367] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.032 seconds
[2023-03-06 02:28:14,736] {processor.py:153} INFO - Started process (PID=4731) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:28:14,738] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:28:14,740] {logging_mixin.py:115} INFO - [2023-03-06 02:28:14,740] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:28:14,747] {logging_mixin.py:115} INFO - [2023-03-06 02:28:14,746] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:28:14,748] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:28:14,764] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.030 seconds
[2023-03-06 02:28:45,038] {processor.py:153} INFO - Started process (PID=4757) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:28:45,039] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:28:45,040] {logging_mixin.py:115} INFO - [2023-03-06 02:28:45,040] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:28:45,049] {logging_mixin.py:115} INFO - [2023-03-06 02:28:45,047] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:28:45,050] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:28:45,065] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 02:29:15,315] {processor.py:153} INFO - Started process (PID=4783) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:29:15,317] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:29:15,318] {logging_mixin.py:115} INFO - [2023-03-06 02:29:15,318] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:29:15,325] {logging_mixin.py:115} INFO - [2023-03-06 02:29:15,324] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:29:15,327] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:29:15,341] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:29:45,737] {processor.py:153} INFO - Started process (PID=4824) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:29:45,738] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:29:45,740] {logging_mixin.py:115} INFO - [2023-03-06 02:29:45,740] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:29:45,748] {logging_mixin.py:115} INFO - [2023-03-06 02:29:45,747] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:29:45,750] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:29:45,763] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:30:16,074] {processor.py:153} INFO - Started process (PID=4857) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:30:16,077] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:30:16,080] {logging_mixin.py:115} INFO - [2023-03-06 02:30:16,079] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:30:16,090] {logging_mixin.py:115} INFO - [2023-03-06 02:30:16,089] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:30:16,093] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:30:16,109] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.039 seconds
[2023-03-06 02:30:46,588] {processor.py:153} INFO - Started process (PID=4906) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:30:46,591] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:30:46,593] {logging_mixin.py:115} INFO - [2023-03-06 02:30:46,593] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:30:46,606] {logging_mixin.py:115} INFO - [2023-03-06 02:30:46,605] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:30:46,607] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:30:46,630] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.044 seconds
[2023-03-06 02:31:17,242] {processor.py:153} INFO - Started process (PID=4982) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:31:17,244] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:31:17,245] {logging_mixin.py:115} INFO - [2023-03-06 02:31:17,245] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:31:17,254] {logging_mixin.py:115} INFO - [2023-03-06 02:31:17,252] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:31:17,255] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:31:17,268] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:31:47,892] {processor.py:153} INFO - Started process (PID=5038) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:31:47,893] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:31:47,895] {logging_mixin.py:115} INFO - [2023-03-06 02:31:47,895] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:31:47,903] {logging_mixin.py:115} INFO - [2023-03-06 02:31:47,901] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:31:47,904] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:31:47,920] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 02:32:18,433] {processor.py:153} INFO - Started process (PID=5089) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:32:18,434] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:32:18,436] {logging_mixin.py:115} INFO - [2023-03-06 02:32:18,436] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:32:18,444] {logging_mixin.py:115} INFO - [2023-03-06 02:32:18,442] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:32:18,445] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:32:18,459] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.027 seconds
[2023-03-06 02:32:48,936] {processor.py:153} INFO - Started process (PID=5135) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:32:48,938] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:32:48,939] {logging_mixin.py:115} INFO - [2023-03-06 02:32:48,939] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:32:48,947] {logging_mixin.py:115} INFO - [2023-03-06 02:32:48,946] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:32:48,948] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:32:48,963] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 02:33:19,681] {processor.py:153} INFO - Started process (PID=5223) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:33:19,683] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:33:19,685] {logging_mixin.py:115} INFO - [2023-03-06 02:33:19,685] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:33:19,695] {logging_mixin.py:115} INFO - [2023-03-06 02:33:19,693] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:33:19,696] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:33:19,708] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.032 seconds
[2023-03-06 02:33:50,510] {processor.py:153} INFO - Started process (PID=5293) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:33:50,512] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:33:50,513] {logging_mixin.py:115} INFO - [2023-03-06 02:33:50,513] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:33:50,525] {logging_mixin.py:115} INFO - [2023-03-06 02:33:50,522] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:33:50,526] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:33:50,542] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.034 seconds
[2023-03-06 02:34:21,003] {processor.py:153} INFO - Started process (PID=5353) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:34:21,006] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:34:21,007] {logging_mixin.py:115} INFO - [2023-03-06 02:34:21,007] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:34:21,016] {logging_mixin.py:115} INFO - [2023-03-06 02:34:21,015] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:34:21,018] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:34:21,033] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.031 seconds
[2023-03-06 02:34:51,620] {processor.py:153} INFO - Started process (PID=5414) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:34:51,622] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:34:51,624] {logging_mixin.py:115} INFO - [2023-03-06 02:34:51,623] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:34:51,632] {logging_mixin.py:115} INFO - [2023-03-06 02:34:51,631] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:34:51,633] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:34:51,646] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:35:22,050] {processor.py:153} INFO - Started process (PID=5460) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:35:22,053] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:35:22,054] {logging_mixin.py:115} INFO - [2023-03-06 02:35:22,054] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:35:22,063] {logging_mixin.py:115} INFO - [2023-03-06 02:35:22,061] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:35:22,064] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:35:22,078] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.030 seconds
[2023-03-06 02:35:52,555] {processor.py:153} INFO - Started process (PID=5514) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:35:52,556] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:35:52,558] {logging_mixin.py:115} INFO - [2023-03-06 02:35:52,558] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:35:52,568] {logging_mixin.py:115} INFO - [2023-03-06 02:35:52,566] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:35:52,569] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:35:52,584] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.031 seconds
[2023-03-06 02:36:23,130] {processor.py:153} INFO - Started process (PID=5562) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:36:23,132] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:36:23,133] {logging_mixin.py:115} INFO - [2023-03-06 02:36:23,133] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:36:23,142] {logging_mixin.py:115} INFO - [2023-03-06 02:36:23,141] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:36:23,143] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:36:23,158] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.030 seconds
[2023-03-06 02:36:53,707] {processor.py:153} INFO - Started process (PID=5613) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:36:53,709] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:36:53,710] {logging_mixin.py:115} INFO - [2023-03-06 02:36:53,710] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:36:53,718] {logging_mixin.py:115} INFO - [2023-03-06 02:36:53,717] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:36:53,720] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:36:53,733] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:37:24,360] {processor.py:153} INFO - Started process (PID=5674) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:37:24,362] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:37:24,363] {logging_mixin.py:115} INFO - [2023-03-06 02:37:24,363] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:37:24,372] {logging_mixin.py:115} INFO - [2023-03-06 02:37:24,370] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:37:24,373] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:37:24,388] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.030 seconds
[2023-03-06 02:37:54,762] {processor.py:153} INFO - Started process (PID=5710) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:37:54,764] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:37:54,765] {logging_mixin.py:115} INFO - [2023-03-06 02:37:54,765] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:37:54,772] {logging_mixin.py:115} INFO - [2023-03-06 02:37:54,771] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:37:54,774] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:37:54,787] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.027 seconds
[2023-03-06 02:38:25,052] {processor.py:153} INFO - Started process (PID=5736) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:38:25,055] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:38:25,055] {logging_mixin.py:115} INFO - [2023-03-06 02:38:25,055] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:38:25,063] {logging_mixin.py:115} INFO - [2023-03-06 02:38:25,062] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:38:25,065] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:38:25,079] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.030 seconds
[2023-03-06 02:38:55,678] {processor.py:153} INFO - Started process (PID=5802) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:38:55,680] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:38:55,681] {logging_mixin.py:115} INFO - [2023-03-06 02:38:55,681] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:38:55,689] {logging_mixin.py:115} INFO - [2023-03-06 02:38:55,687] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:38:55,690] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:38:55,703] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.027 seconds
[2023-03-06 02:39:26,060] {processor.py:153} INFO - Started process (PID=5839) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:39:26,061] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:39:26,063] {logging_mixin.py:115} INFO - [2023-03-06 02:39:26,063] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:39:26,071] {logging_mixin.py:115} INFO - [2023-03-06 02:39:26,069] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:39:26,072] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:39:26,086] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.028 seconds
[2023-03-06 02:39:56,432] {processor.py:153} INFO - Started process (PID=5874) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:39:56,433] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:39:56,435] {logging_mixin.py:115} INFO - [2023-03-06 02:39:56,435] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:39:56,443] {logging_mixin.py:115} INFO - [2023-03-06 02:39:56,442] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:39:56,446] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:39:56,459] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.029 seconds
[2023-03-06 02:40:26,850] {processor.py:153} INFO - Started process (PID=5900) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:40:26,852] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:40:26,853] {logging_mixin.py:115} INFO - [2023-03-06 02:40:26,853] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:40:26,865] {logging_mixin.py:115} INFO - [2023-03-06 02:40:26,863] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:40:26,867] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:40:26,885] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.040 seconds
[2023-03-06 02:40:57,186] {processor.py:153} INFO - Started process (PID=5931) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:40:57,187] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:40:57,188] {logging_mixin.py:115} INFO - [2023-03-06 02:40:57,188] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:40:57,197] {logging_mixin.py:115} INFO - [2023-03-06 02:40:57,196] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:40:57,198] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:40:57,213] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.030 seconds
[2023-03-06 02:41:27,592] {processor.py:153} INFO - Started process (PID=5957) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:41:27,593] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:41:27,595] {logging_mixin.py:115} INFO - [2023-03-06 02:41:27,595] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:41:27,604] {logging_mixin.py:115} INFO - [2023-03-06 02:41:27,601] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:41:27,605] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:41:27,621] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.031 seconds
[2023-03-06 02:41:58,019] {processor.py:153} INFO - Started process (PID=5983) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:41:58,021] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:41:58,023] {logging_mixin.py:115} INFO - [2023-03-06 02:41:58,023] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:41:58,036] {logging_mixin.py:115} INFO - [2023-03-06 02:41:58,034] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:41:58,038] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:41:58,055] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.041 seconds
[2023-03-06 02:42:28,365] {processor.py:153} INFO - Started process (PID=6027) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:42:28,368] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:42:28,371] {logging_mixin.py:115} INFO - [2023-03-06 02:42:28,371] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:42:28,383] {logging_mixin.py:115} INFO - [2023-03-06 02:42:28,380] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:42:28,384] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:42:28,400] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.039 seconds
[2023-03-06 02:42:58,804] {processor.py:153} INFO - Started process (PID=6053) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:42:58,807] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:42:58,810] {logging_mixin.py:115} INFO - [2023-03-06 02:42:58,810] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:42:58,825] {logging_mixin.py:115} INFO - [2023-03-06 02:42:58,823] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:42:58,827] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:42:58,841] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.042 seconds
[2023-03-06 02:43:29,263] {processor.py:153} INFO - Started process (PID=6079) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:43:29,267] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:43:29,268] {logging_mixin.py:115} INFO - [2023-03-06 02:43:29,268] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:43:29,279] {logging_mixin.py:115} INFO - [2023-03-06 02:43:29,277] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:43:29,281] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:43:29,295] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.037 seconds
[2023-03-06 02:43:59,593] {processor.py:153} INFO - Started process (PID=6105) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:43:59,596] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:43:59,598] {logging_mixin.py:115} INFO - [2023-03-06 02:43:59,598] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:43:59,609] {logging_mixin.py:115} INFO - [2023-03-06 02:43:59,607] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:43:59,611] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:43:59,625] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.037 seconds
[2023-03-06 02:44:30,027] {processor.py:153} INFO - Started process (PID=6131) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:44:30,030] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:44:30,032] {logging_mixin.py:115} INFO - [2023-03-06 02:44:30,031] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:44:30,043] {logging_mixin.py:115} INFO - [2023-03-06 02:44:30,041] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:44:30,044] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:44:30,060] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.037 seconds
[2023-03-06 02:45:00,377] {processor.py:153} INFO - Started process (PID=6157) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:45:00,379] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:45:00,381] {logging_mixin.py:115} INFO - [2023-03-06 02:45:00,381] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:45:00,396] {logging_mixin.py:115} INFO - [2023-03-06 02:45:00,393] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:45:00,398] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:45:00,416] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.044 seconds
[2023-03-06 02:45:30,800] {processor.py:153} INFO - Started process (PID=6183) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:45:30,802] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:45:30,803] {logging_mixin.py:115} INFO - [2023-03-06 02:45:30,803] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:45:30,811] {logging_mixin.py:115} INFO - [2023-03-06 02:45:30,809] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:45:30,812] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:45:30,825] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.026 seconds
[2023-03-06 02:46:01,083] {processor.py:153} INFO - Started process (PID=6209) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:46:01,085] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:46:01,086] {logging_mixin.py:115} INFO - [2023-03-06 02:46:01,086] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:46:01,096] {logging_mixin.py:115} INFO - [2023-03-06 02:46:01,094] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:46:01,097] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:46:01,111] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.031 seconds
[2023-03-06 02:46:31,401] {processor.py:153} INFO - Started process (PID=6235) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:46:31,403] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:46:31,404] {logging_mixin.py:115} INFO - [2023-03-06 02:46:31,404] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:46:31,412] {logging_mixin.py:115} INFO - [2023-03-06 02:46:31,410] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:46:31,413] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:46:31,430] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.031 seconds
[2023-03-06 02:47:01,724] {processor.py:153} INFO - Started process (PID=6261) to work on /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:47:01,726] {processor.py:641} INFO - Processing file /opt/airflow/dags/Proyecto/ingest.py for tasks to queue
[2023-03-06 02:47:01,727] {logging_mixin.py:115} INFO - [2023-03-06 02:47:01,727] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:47:01,736] {logging_mixin.py:115} INFO - [2023-03-06 02:47:01,734] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Proyecto/ingest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Proyecto/ingest.py", line 1, in <module>
    import process.name as n
ModuleNotFoundError: No module named 'process'
[2023-03-06 02:47:01,737] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Proyecto/ingest.py
[2023-03-06 02:47:01,752] {processor.py:161} INFO - Processing /opt/airflow/dags/Proyecto/ingest.py took 0.030 seconds
