[2023-03-10 00:52:59,139] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-10T00:52:40.263955+00:00 [queued]>
[2023-03-10 00:52:59,145] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-10T00:52:40.263955+00:00 [queued]>
[2023-03-10 00:52:59,145] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-10 00:52:59,146] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-10 00:52:59,147] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-10 00:52:59,156] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_script_transform> on 2023-03-10 00:52:40.263955+00:00
[2023-03-10 00:52:59,159] {standard_task_runner.py:52} INFO - Started process 485 to run task
[2023-03-10 00:52:59,162] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_bash_operator', 'run_script_transform', 'manual__2023-03-10T00:52:40.263955+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_bash_operator.py', '--cfg-path', '/tmp/tmpmqwpueg6', '--error-file', '/tmp/tmphlhvqain']
[2023-03-10 00:52:59,163] {standard_task_runner.py:80} INFO - Job 65: Subtask run_script_transform
[2023-03-10 00:52:59,200] {task_command.py:369} INFO - Running <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-10T00:52:40.263955+00:00 [running]> on host 477ef5e408be
[2023-03-10 00:52:59,242] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Americo
AIRFLOW_CTX_DAG_ID=pipeline_bash_operator
AIRFLOW_CTX_TASK_ID=run_script_transform
AIRFLOW_CTX_EXECUTION_DATE=2023-03-10T00:52:40.263955+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-10T00:52:40.263955+00:00
[2023-03-10 00:52:59,243] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-03-10 00:52:59,245] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/dags/Proyecto/transform.py']
[2023-03-10 00:52:59,253] {subprocess.py:85} INFO - Output:
[2023-03-10 00:53:26,868] {subprocess.py:92} INFO - ingest loaded
[2023-03-10 00:53:26,872] {subprocess.py:92} INFO - loaded adsl landing
[2023-03-10 00:53:26,875] {subprocess.py:92} INFO - transform loaded
[2023-03-10 00:53:26,878] {subprocess.py:92} INFO - loaded adsl gold
[2023-03-10 00:53:26,885] {subprocess.py:92} INFO - Traceback (most recent call last):
[2023-03-10 00:53:26,887] {subprocess.py:92} INFO -   File "/opt/***/dags/Proyecto/transform.py", line 29, in <module>
[2023-03-10 00:53:26,889] {subprocess.py:92} INFO -     load.load_mysql(df_enunciado1, "enunciado1")
[2023-03-10 00:53:26,890] {subprocess.py:92} INFO -   File "/opt/***/dags/Proyecto/process/load.py", line 28, in load_mysql
[2023-03-10 00:53:26,892] {subprocess.py:92} INFO -     u.df_to_mysql(df, u.mysql_engine(), db_tbl_name)
[2023-03-10 00:53:26,894] {subprocess.py:92} INFO -   File "/opt/***/dags/Proyecto/process/util/utils.py", line 21, in mysql_engine
[2023-03-10 00:53:26,896] {subprocess.py:92} INFO -     engine = create_engine("mysql://{0}:{1}@{2}:{3}/{4}?charset=utf8".format(user, password, host, port, database))
[2023-03-10 00:53:26,897] {subprocess.py:92} INFO -   File "<string>", line 2, in create_engine
[2023-03-10 00:53:26,899] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
[2023-03-10 00:53:26,900] {subprocess.py:92} INFO -     return fn(*args, **kwargs)
[2023-03-10 00:53:26,902] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
[2023-03-10 00:53:26,903] {subprocess.py:92} INFO -     dbapi = dialect_cls.dbapi(**dbapi_args)
[2023-03-10 00:53:26,904] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
[2023-03-10 00:53:26,907] {subprocess.py:92} INFO -     return __import__("MySQLdb")
[2023-03-10 00:53:26,908] {subprocess.py:92} INFO - ModuleNotFoundError: No module named 'MySQLdb'
[2023-03-10 00:53:26,980] {subprocess.py:96} INFO - Command exited with return code 1
[2023-03-10 00:53:26,991] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-10 00:53:26,996] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=pipeline_bash_operator, task_id=run_script_transform, execution_date=20230310T005240, start_date=20230310T005259, end_date=20230310T005326
[2023-03-10 00:53:27,006] {standard_task_runner.py:97} ERROR - Failed to execute job 65 for task run_script_transform (Bash command failed. The command returned a non-zero exit code 1.; 485)
[2023-03-10 00:53:27,016] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-10 00:53:27,033] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
