[2023-03-08 01:28:37,969] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-08T01:28:19.034937+00:00 [queued]>
[2023-03-08 01:28:37,976] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-08T01:28:19.034937+00:00 [queued]>
[2023-03-08 01:28:37,977] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-08 01:28:37,978] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-08 01:28:37,979] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-08 01:28:37,987] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_script_transform> on 2023-03-08 01:28:19.034937+00:00
[2023-03-08 01:28:37,991] {standard_task_runner.py:52} INFO - Started process 2055 to run task
[2023-03-08 01:28:37,994] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_bash_operator', 'run_script_transform', 'manual__2023-03-08T01:28:19.034937+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_bash_operator.py', '--cfg-path', '/tmp/tmpxs5vs3z_', '--error-file', '/tmp/tmpowaetvi8']
[2023-03-08 01:28:37,995] {standard_task_runner.py:80} INFO - Job 60: Subtask run_script_transform
[2023-03-08 01:28:38,035] {task_command.py:369} INFO - Running <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-08T01:28:19.034937+00:00 [running]> on host 477ef5e408be
[2023-03-08 01:28:38,081] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Americo
AIRFLOW_CTX_DAG_ID=pipeline_bash_operator
AIRFLOW_CTX_TASK_ID=run_script_transform
AIRFLOW_CTX_EXECUTION_DATE=2023-03-08T01:28:19.034937+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-08T01:28:19.034937+00:00
[2023-03-08 01:28:38,083] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-03-08 01:28:38,084] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/dags/Proyecto/transform.py']
[2023-03-08 01:28:38,091] {subprocess.py:85} INFO - Output:
[2023-03-08 01:29:05,361] {subprocess.py:92} INFO - ingest loaded
[2023-03-08 01:29:05,362] {subprocess.py:92} INFO - loaded adsl landing
[2023-03-08 01:29:05,364] {subprocess.py:92} INFO - transform loaded
[2023-03-08 01:29:05,365] {subprocess.py:92} INFO - loaded adsl gold
[2023-03-08 01:29:05,369] {subprocess.py:92} INFO - Traceback (most recent call last):
[2023-03-08 01:29:05,370] {subprocess.py:92} INFO -   File "/opt/***/dags/Proyecto/transform.py", line 34, in <module>
[2023-03-08 01:29:05,370] {subprocess.py:92} INFO -     load.load_mysql(df_enunciado1, enunciado1)
[2023-03-08 01:29:05,371] {subprocess.py:92} INFO -   File "/opt/***/dags/Proyecto/process/load.py", line 28, in load_mysql
[2023-03-08 01:29:05,372] {subprocess.py:92} INFO -     u.df_to_mysql(df, u.mysql_engine(), db_tbl_name)
[2023-03-08 01:29:05,373] {subprocess.py:92} INFO -   File "/opt/***/dags/Proyecto/process/util/utils.py", line 21, in mysql_engine
[2023-03-08 01:29:05,374] {subprocess.py:92} INFO -     engine = create_engine("mysql://{0}:{1}@{2}:{3}/{4}?charset=utf8".format(user, password, host, port, database))
[2023-03-08 01:29:05,375] {subprocess.py:92} INFO -   File "<string>", line 2, in create_engine
[2023-03-08 01:29:05,376] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
[2023-03-08 01:29:05,376] {subprocess.py:92} INFO -     return fn(*args, **kwargs)
[2023-03-08 01:29:05,377] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
[2023-03-08 01:29:05,378] {subprocess.py:92} INFO -     dbapi = dialect_cls.dbapi(**dbapi_args)
[2023-03-08 01:29:05,379] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
[2023-03-08 01:29:05,381] {subprocess.py:92} INFO -     return __import__("MySQLdb")
[2023-03-08 01:29:05,382] {subprocess.py:92} INFO - ModuleNotFoundError: No module named 'MySQLdb'
[2023-03-08 01:29:05,469] {subprocess.py:96} INFO - Command exited with return code 1
[2023-03-08 01:29:05,480] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-08 01:29:05,484] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=pipeline_bash_operator, task_id=run_script_transform, execution_date=20230308T012819, start_date=20230308T012837, end_date=20230308T012905
[2023-03-08 01:29:05,494] {standard_task_runner.py:97} ERROR - Failed to execute job 60 for task run_script_transform (Bash command failed. The command returned a non-zero exit code 1.; 2055)
[2023-03-08 01:29:05,501] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-08 01:29:05,518] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
